### ISSUE TITLE
Update Virtualbox.Extensionpack

### ISSUE THREAD

**Issue by NicoHaase** [michaelray/ChocolateyPackages#6]
Once more, there has been an update for the VirtualBox package, and the extension package needs an update too

**Comment by michaelray** [comment]
Actually, it looks like the latest update to the VirtualBox package that you're referring to ( https://chocolatey.org/packages/virtualbox/5.1.10.20161203 ) was done to add the installation of the extension pack from within that package itself by default, unless you specify a parameter to not install the extension pack (NoExtensionPack).  You can see it on package page at the link above, under the "Package parameters" section.

This means that the VirtualBox.ExtensionPack package is being obsoleted in favor of having both VB and the ext pack installed via the same package (which should prevent the version discrepancies going forward).  This also means that updating the VirtualBox.ExtensionPack package to work with the latest VirtualBox package version is probably unnecessary (but I'll do some testing to verify and update later on, this evening probably).

I haven't upgraded my VB package locally yet, so I'm not sure what implications there are of having the extension pack installed through the VB package and also through the ext pack package.  It certainly wouldn't make much sense to install the extension pack twice, though.

**Comment by NicoHaase** [comment]
Yeah, it looks like your package got obsolete now.... After having it uninstalled, I could update virtualbox as usual and it also downloaded the extension pack itself
